"language_fundamentals",
"ruby_syntax_execution_model", 
"objectoriented_programming", 
"Ruby Object Model",
"Variables, Scope & Constants",
"Methods & Argument Handling",
"Blocks, Procs & Lambdas",
"Symbols vs Strings",
"Exception Handling & Error Design",
"Ruby Collections & Enumerables",
"Ruby Memory Management & Garbage Collection",
"Ruby Metaprogramming",
"Method Lookup Chain",
"Reflection & Introspection",
"Monkey Patching & Risks",
"Ruby Concurrency (Thread, Fiber, Ractor)",
"Mutex & Race Conditions",
"Ruby Performance Optimization",
"Ruby Standard Library",
"Ruby Tooling (rbenv, RVM, Bundler)",
"Gems & Dependency Management",
"Writing Custom Gems",
"Semantic Versioning & Dependency Resolution",
"Rails Philosophy & Design Principles",
"Convention over Configuration",
"MVC Architecture Deep Dive",
"Rails Application Structure",
"Rails Boot & Initialization Process",
"Zeitwerk Autoloading",
"Railties & Engines",
"Rails Command Line Tools",
"Rails Request Lifecycle",
"Rack Interface & Middleware Stack",
"HTTP Fundamentals for Rails",
"Routing System Architecture",
"RESTful Routing",
"Advanced Routing Techniques",
"Controllers & Request Handling",
"Strong Parameters & Security",
"Filters & Controller Callbacks",
"Rendering Pipeline",
"Sessions, Cookies & Flash",
"API Controllers",
"Views & Rendering System",
"ERB Templating",
"Partials & Layouts",
"View Helpers",
"View Components Architecture",
"Hotwire (Turbo Drive)",
"Turbo Frames & Turbo Streams",
"StimulusJS Integration",
"Asset Pipeline & Asset Management",
"ActiveRecord Fundamentals",
"Database Migrations & Schema Management",
"CRUD Operations Internals",
"ActiveRecord Associations",
"Polymorphic Associations",
"Single Table Inheritance (STI)",
"Validations & Custom Validators",
"ActiveRecord Callbacks",
"Advanced ActiveRecord",
"Query Interface Deep Dive",
"Scopes & Query Objects",
"Joins vs Includes vs Preload",
"Eager Loading Strategies",
"N+1 Query Detection",
"Transactions & Rollbacks",
"Optimistic & Pessimistic Locking",
"Batch Processing & Bulk Operations",
"Database Constraints vs Model Validations",
"Database Engineering",
"Relational Database Design",
"Normalization vs Denormalization",
"PostgreSQL Internals",
"Indexing Strategies",
"Query Optimization & EXPLAIN ANALYZE",
"Connection Pooling",
"Read Replicas & Replication",
"Database Sharding",
"Authentication Systems",
"Session-Based Authentication",
"Token-Based Authentication (JWT)",
"OAuth & Social Login",
"Devise Architecture",
"Authorization (Pundit / CanCanCan)",
"Role-Based Access Control",
"API Development",
"API-Only Rails Applications",
"REST API Design Principles",
"JSON Serialization Strategies",
"API Versioning",
"Pagination & Filtering",
"Rate Limiting & Throttling",
"Idempotency in APIs",
"CORS Handling",
"Background Processing",
"ActiveJob Architecture",
"Sidekiq Internals",
"Redis Fundamentals",
"Job Retries & Dead Queues",
"Scheduled Jobs & Cron Systems",
"Idempotent Job Design",
"Queue Prioritization",
"Caching Strategies",
"Low-Level Caching",
"Fragment Caching",
"Russian Doll Caching",
"HTTP Caching",
"Redis Cache Store",
"Cache Invalidation Strategies",
"Cache Stampede Prevention",
"File Upload & Media Handling",
"ActiveStorage Architecture",
"Image Processing Pipelines",
"CDN Integration",
"Cloud Storage (AWS S3)",
"Real-Time Systems",
"ActionCable Architecture",
"WebSockets Fundamentals",
"Pub/Sub Systems",
"Turbo Stream Realtime Updates",
"Performance Optimization",
"Application Profiling",
"Memory Profiling",
"Benchmarking Techniques",
"Query Performance Tuning",
"Concurrency Optimization",
"Rails Security",
"SQL Injection Prevention",
"Cross-Site Scripting (XSS)",
"CSRF Protection",
"Secure Cookies & Sessions",
"Content Security Policy (CSP)",
"Encryption & Credentials Management",
"Testing Ecosystem",
"RSpec Fundamentals",
"Minitest",
"Model, Request & System Specs",
"FactoryBot",
"Mocking & Stubbing",
"Test Performance Optimization",
"Observability & Debugging",
"Rails Logging System",
"Structured Logging",
"Error Tracking (Sentry)",
"Performance Monitoring",
"Production Debugging Techniques",
"Architecture Patterns",
"Service Objects",
"Form Objects",
"Query Objects",
"Decorators & Presenters",
"Domain-Driven Design",
"Monolith vs Microservices",
"Deployment & Infrastructure",
"Puma Application Server",
"Nginx & Reverse Proxy",
"Docker for Rails",
"CI/CD Pipelines",
"Capistrano Deployment",
"Production Scaling",
"Horizontal Scaling",
"Load Balancing",
"Background Worker Scaling",
"CDN Architecture",
"Multi-Region Deployment",
"DevOps for Rails",
"Environment Configuration",
"Secrets Management",
"Zero-Downtime Deployment",
"Blue-Green Deployment",
"Rolling Deployments",
"Health Checks & Monitoring",
"Networking Fundamentals",
"DNS Architecture",
"HTTP/HTTPS Protocol",
"SSL/TLS Handshake",
"Reverse Proxy Concepts",
"Distributed Systems Concepts",
"Message Queues (Kafka/RabbitMQ)",
"Event-Driven Architecture",
"Consistency Models",
"Fault Tolerance",
"System Design with Rails",
"Designing a Booking System",
"URL Shortener Architecture",
"Messaging System Design",
"Multi-Tenant SaaS Architecture",
"High-Traffic API Design",
"Production Problem Solving",
"Race Conditions",
"Deadlocks",
"Memory Leaks",
"Slow Queries",
"Background Job Failures",
"Algorithms & Data Structures for Backend",
"Caching Data Structures",
"Bloom Filters & Redis Usage",
"Search Optimization Techniques",
"AI & Modern Backend Integration",
"LLM Integration in Rails",
"Embeddings & Vector Databases",
"Retrieval-Augmented Generation (RAG)",
"Engineering Practices",
"SOLID Principles",
"Code Smells & Refactoring",
"RuboCop & Linting",
"Code Reviews & Mentoring",
"Technical Decision Making",
"Interview Preparation & Debug Scenarios",
"Debugging Slow Endpoints",
"Safe Database Migrations",
"Fixing N+1 Queries",
"Scaling Legacy Applications"
]





# im a rails 15 yr old develper & im starting my journy again so i wnt to learn from strach

# ans according to u make it simple & clear so i can understand & crack the interview

#  i wnt to deep dive in every topic 
# make desirable changes in file i wnt to read & learn need to crack interview & also wnt to get knowledge of everything

# ans all question in deeply one by one - lets strat from first file

# 1 every single ans should be very simple
# 2 explainable everything
# 3 deepdive in everytopic
# 4 make ans very long & simple
# 5 detail explaination of everything

 

rails how it works
how migration works in rails 
how to migrate data on prod
booking system works- all kind
action cable
threads - all kind
booking logic
all type of indexing
WebSockets vs HTTP
Scaling Action Cable: Redis, threads, horizontal servers.
 concurrency, GIL, Ruby limitations
